controller_manager:
  ros__parameters:
    update_rate: 20  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    #gripper_controller:
    # type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - joint_link_1
      - joint_link_2
      - joint_link_3
      - joint_link_4

    command_interfaces:
      - position

    state_interfaces:
      - position

    open_loop_control: false
    allow_integration_in_goal_trajectories: true
